admin:
    app_name: Dinkly Admin
    base_href: /admin
    default_module: home
api:
    app_name: Dinkly API
    base_href: /api
    default_module: api
content:
    app_name: School Me
    app_description: See which school district is best for you.
    default_app: true
    base_href: /
    default_module: main